SELECT  C.CUST_ID, C.USERNAME, R.RELOAD_ID, R."DATE", R."TIME", R.AMOUNT, S.USERNAME
FROM CUSTOMER C INNER JOIN  RELOAD R ON C.CUST_ID = R.CUST_ID
INNER JOIN STAFF S ON S.STAFF_ID = R.STAFF_ID
WHERE MONTH(R."DATE") = 2
OFFSET 5 ROWS FETCH NEXT 10 ROWS ONLY

//TOTAL AMOUNT
SELECT COUNT(*) AS TOTAL_NUMBER_OF_TOPUP, SUM(R.AMOUNT) AS TOTAL_AMOUNT
FROM CUSTOMER C INNER JOIN  RELOAD R ON C.CUST_ID = R.CUST_ID
INNER JOIN STAFF S ON S.STAFF_ID = R.STAFF_ID
WHERE MONTH(R."DATE") = 3