SELECT OL.MEAL_ID, M."NAME", COUNT(M.MEAL_ID) AS TOTAL_FOOD_ORDERED
FROM ORDERMEAL O INNER JOIN  ORDERLIST OL ON O.ORDER_ID = OL.ORDER_ID
INNER JOIN MEAL M ON OL.MEAL_ID = M.MEAL_ID
INNER JOIN COUPON C ON OL.COUPON_ID = C.COUPON_ID
WHERE MONTH(C.REDEEM_DATE) = 4
GROUP BY OL.MEAL_ID, M."NAME", MONTH(C.REDEEM_DATE)
ORDER BY COUNT(M.MEAL_ID) DESC