/*
Derby DBMS Reserved Keywords
https://db.apache.org/derby/docs/10.2/ref/rrefkeywords29722.html
*/

CREATE TABLE CUSTOMER (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	USERNAME VARCHAR(30),
	EMAIL VARCHAR(50) UNIQUE,
	PASSWORD VARCHAR(30),
	CREDITPOINTS INTEGER NOT NULL WITH DEFAULT 0,
PRIMARY KEY (ID)
);

/* We might need a CRUD for this */
CREATE TABLE CATEGORY (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR (80) NOT NULL,
	DESCRIPTION VARCHAR(255),
	IMAGE BLOB,
PRIMARY KEY (ID)
);

CREATE TABLE MEAL (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(80) NOT NULL,
	DESCRIPTION VARCHAR(255),
	DAY VARBINARY(6) NOT NULL,
	PRICE DOUBLE NOT NULL,
	INGREDIENT VARCHAR(80) NOT NULL,
	INGREDIENT_QTY INTEGER NOT NULL,
	CALORIES INTEGER NOT NULL,
	IMAGE BLOB,
	CATEGORYID INTEGER NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORYID) REFERENCES CATEGORY(ID)
);

CREATE TABLE PAYMENT (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	"DATE" DATE NOT NULL WITH DEFAULT CURRENT DATE,
	"TIME" TIME NOT NULL WITH DEFAULT CURRENT TIME,
	AMOUNT DOUBLE NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE MEALORDER (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	STUTUS VARCHAR(10) NOT NULL,
	REDEEM_DATE DATE,
	REDEEM_TIME TIME,
	PAYMENTID INTEGER NOT NULL,
	CUSTID INTEGER NOT NULL,
	CATEGORYID INTEGER NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (PAYMENTID) REFERENCES PAYMENT(ID),
FOREIGN KEY (CUSTID) REFERENCES CUSTOMER(ID),
FOREIGN KEY (CATEGORYID) REFERENCES CATEGORY(ID),
CONSTRAINT CHK_STUTUS CHECK (STUTUS IN ('Paid','Redeemed','Canceled','Expired'))
);

CREATE TABLE ORDERLIST (
	MEALID INTEGER NOT NULL,
	ORDERID INTEGER NOT NULL,
	QUANTITY INTEGER NOT NULL WITH DEFAULT 1,
PRIMARY KEY (MEALID, ORDERID),
FOREIGN KEY(MEALID) REFERENCES MEAL(ID),
FOREIGN KEY(ORDERID) REFERENCES MEALORDER(ID)
);

CREATE TABLE STAFF (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	USERNAME VARCHAR(255),
	EMAIL VARCHAR(50) UNIQUE,
	PASSWORD VARCHAR(30),
	CATEGORYID INTEGER,
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORYID) REFERENCES CATEGORY(ID)
);

CREATE TABLE RELOAD (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	"DATE" DATE NOT NULL WITH DEFAULT CURRENT DATE,
	"TIME" TIME NOT NULL WITH DEFAULT CURRENT TIME,
	AMOUNT DOUBLE NOT NULL,
	CUSTID INTEGER,
	STAFFID INTEGER,
PRIMARY KEY (ID),
FOREIGN KEY (CUSTID) REFERENCES CUSTOMER(ID),
FOREIGN KEY (STAFFID) REFERENCES STAFF(ID)
);
